/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Debug0_aliases.h>
#include <Debug0.h>
#include <Debug1_aliases.h>
#include <Debug1.h>
#include <PiComs.h>
#include <PiComs_PVT.h>
#include <SpiXmitDma_dma.h>
#include <PiSPI_MOSI_aliases.h>
#include <PiSPI_MOSI.h>
#include <PiSPI_SCLK_aliases.h>
#include <PiSPI_SCLK.h>
#include <PiSPI_SS_aliases.h>
#include <PiSPI_SS.h>
#include <PiSPI_MISO_aliases.h>
#include <PiSPI_MISO.h>
#include <PiSPI_CLK.h>
#include <Debug2_aliases.h>
#include <Debug2.h>
#include <Debug3_aliases.h>
#include <Debug3.h>
#include <Debug4_aliases.h>
#include <Debug4.h>
#include <Debug5_aliases.h>
#include <Debug5.h>
#include <Debug6_aliases.h>
#include <Debug6.h>
#include <Debug7_aliases.h>
#include <Debug7.h>
#include <SpiRcvDma_dma.h>
#include <SpiXferDone.h>
#include <RDV2_aliases.h>
#include <RDV2.h>
#include <RDG2_aliases.h>
#include <RDG2.h>
#include <RDV1_aliases.h>
#include <RDV1.h>
#include <RDG1_aliases.h>
#include <RDG1.h>
#include <LDV2_aliases.h>
#include <LDV2.h>
#include <LDV1_aliases.h>
#include <LDV1.h>
#include <LDG2_aliases.h>
#include <LDG2.h>
#include <LDG1_aliases.h>
#include <LDG1.h>
#include <LMotorPwm.h>
#include <MotorPwmClock.h>
#include <RMotorPwm.h>
#include <MotorControlReg.h>
#include <SerDrv_485Sel_aliases.h>
#include <SerDrv_485Sel.h>
#include <SerDrv_Enable_aliases.h>
#include <SerDrv_Enable.h>
#include <SerDrv_RA_aliases.h>
#include <SerDrv_RA.h>
#include <SerDrv_RB_aliases.h>
#include <SerDrv_RB.h>
#include <SerDrv_DY_aliases.h>
#include <SerDrv_DY.h>
#include <SerDrv_DZ_aliases.h>
#include <SerDrv_DZ.h>
#include <PiUART_RXD_aliases.h>
#include <PiUART_RXD.h>
#include <PiUART_TXD_aliases.h>
#include <PiUART_TXD.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

